[theme]

primaryColor = "#919e8b" # green
backgroundColor = "rgba(254,248,239,1)" # sepia yellow
secondaryBackgroundColor =  "#ebd2b9" # wheat  "#d7ab82" # yellow <-- not enough contrast
textColor = "#6e7074" # grey
font = "sans serif"
